package com.gz.tzreport.pojo;

import java.util.Date;

public class TbAdvice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.advice_id
     *
     * @mbg.generated
     */
    private Integer adviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.advice_title
     *
     * @mbg.generated
     */
    private String adviceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.advice_body
     *
     * @mbg.generated
     */
    private String adviceBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.advice_telephone
     *
     * @mbg.generated
     */
    private String adviceTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_advice.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.advice_id
     *
     * @return the value of tb_advice.advice_id
     *
     * @mbg.generated
     */
    public Integer getAdviceId() {
        return adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advice.advice_id
     *
     * @param adviceId the value for tb_advice.advice_id
     *
     * @mbg.generated
     */
    public void setAdviceId(Integer adviceId) {
        this.adviceId = adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.advice_title
     *
     * @return the value of tb_advice.advice_title
     *
     * @mbg.generated
     */
    public String getAdviceTitle() {
        return adviceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advice.advice_title
     *
     * @param adviceTitle the value for tb_advice.advice_title
     *
     * @mbg.generated
     */
    public void setAdviceTitle(String adviceTitle) {
        this.adviceTitle = adviceTitle == null ? null : adviceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.advice_body
     *
     * @return the value of tb_advice.advice_body
     *
     * @mbg.generated
     */
    public String getAdviceBody() {
        return adviceBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advice.advice_body
     *
     * @param adviceBody the value for tb_advice.advice_body
     *
     * @mbg.generated
     */
    public void setAdviceBody(String adviceBody) {
        this.adviceBody = adviceBody == null ? null : adviceBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.advice_telephone
     *
     * @return the value of tb_advice.advice_telephone
     *
     * @mbg.generated
     */
    public String getAdviceTelephone() {
        return adviceTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advice.advice_telephone
     *
     * @param adviceTelephone the value for tb_advice.advice_telephone
     *
     * @mbg.generated
     */
    public void setAdviceTelephone(String adviceTelephone) {
        this.adviceTelephone = adviceTelephone == null ? null : adviceTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.create_time
     *
     * @return the value of tb_advice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advice.create_time
     *
     * @param createTime the value for tb_advice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_advice.update_time
     *
     * @return the value of tb_advice.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_advice.update_time
     *
     * @param updateTime the value for tb_advice.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}