package com.gz.tzreport.pojo;

import java.util.Date;

public class TbArticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_link
     *
     * @mbg.generated
     */
    private String articleLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_platform
     *
     * @mbg.generated
     */
    private String articlePlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_category
     *
     * @mbg.generated
     */
    private String articleCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_descript
     *
     * @mbg.generated
     */
    private String articleDescript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_body
     *
     * @mbg.generated
     */
    private String articleBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.article_image
     *
     * @mbg.generated
     */
    private String articleImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_id
     *
     * @return the value of tb_article.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_id
     *
     * @param articleId the value for tb_article.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_title
     *
     * @return the value of tb_article.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_title
     *
     * @param articleTitle the value for tb_article.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_link
     *
     * @return the value of tb_article.article_link
     *
     * @mbg.generated
     */
    public String getArticleLink() {
        return articleLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_link
     *
     * @param articleLink the value for tb_article.article_link
     *
     * @mbg.generated
     */
    public void setArticleLink(String articleLink) {
        this.articleLink = articleLink == null ? null : articleLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_platform
     *
     * @return the value of tb_article.article_platform
     *
     * @mbg.generated
     */
    public String getArticlePlatform() {
        return articlePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_platform
     *
     * @param articlePlatform the value for tb_article.article_platform
     *
     * @mbg.generated
     */
    public void setArticlePlatform(String articlePlatform) {
        this.articlePlatform = articlePlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_category
     *
     * @return the value of tb_article.article_category
     *
     * @mbg.generated
     */
    public String getArticleCategory() {
        return articleCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_category
     *
     * @param articleCategory the value for tb_article.article_category
     *
     * @mbg.generated
     */
    public void setArticleCategory(String articleCategory) {
        this.articleCategory = articleCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_descript
     *
     * @return the value of tb_article.article_descript
     *
     * @mbg.generated
     */
    public String getArticleDescript() {
        return articleDescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_descript
     *
     * @param articleDescript the value for tb_article.article_descript
     *
     * @mbg.generated
     */
    public void setArticleDescript(String articleDescript) {
        this.articleDescript = articleDescript == null ? null : articleDescript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_body
     *
     * @return the value of tb_article.article_body
     *
     * @mbg.generated
     */
    public String getArticleBody() {
        return articleBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_body
     *
     * @param articleBody the value for tb_article.article_body
     *
     * @mbg.generated
     */
    public void setArticleBody(String articleBody) {
        this.articleBody = articleBody == null ? null : articleBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.article_image
     *
     * @return the value of tb_article.article_image
     *
     * @mbg.generated
     */
    public String getArticleImage() {
        return articleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.article_image
     *
     * @param articleImage the value for tb_article.article_image
     *
     * @mbg.generated
     */
    public void setArticleImage(String articleImage) {
        this.articleImage = articleImage == null ? null : articleImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.create_time
     *
     * @return the value of tb_article.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.create_time
     *
     * @param createTime the value for tb_article.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.update_time
     *
     * @return the value of tb_article.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.update_time
     *
     * @param updateTime the value for tb_article.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}