package com.gz.tzreport.pojo;

import java.util.Date;

public class TbRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_leve
     *
     * @mbg.generated
     */
    private String roleLeve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_id
     *
     * @return the value of tb_roles.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_id
     *
     * @param roleId the value for tb_roles.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_name
     *
     * @return the value of tb_roles.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_name
     *
     * @param roleName the value for tb_roles.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_leve
     *
     * @return the value of tb_roles.role_leve
     *
     * @mbg.generated
     */
    public String getRoleLeve() {
        return roleLeve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_leve
     *
     * @param roleLeve the value for tb_roles.role_leve
     *
     * @mbg.generated
     */
    public void setRoleLeve(String roleLeve) {
        this.roleLeve = roleLeve == null ? null : roleLeve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.create_time
     *
     * @return the value of tb_roles.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.create_time
     *
     * @param createTime the value for tb_roles.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.update_time
     *
     * @return the value of tb_roles.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.update_time
     *
     * @param updateTime the value for tb_roles.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}