package com.gz.tzreport.pojo;

import java.util.Date;

public class TbUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_telephone
     *
     * @mbg.generated
     */
    private String userTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_role
     *
     * @mbg.generated
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_token
     *
     * @mbg.generated
     */
    private String userToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.user_state
     *
     * @mbg.generated
     */
    private String userState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.head_image
     *
     * @mbg.generated
     */
    private String headImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_users.online_state
     *
     * @mbg.generated
     */
    private String onlineState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_id
     *
     * @return the value of tb_users.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_id
     *
     * @param userId the value for tb_users.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_name
     *
     * @return the value of tb_users.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_name
     *
     * @param userName the value for tb_users.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_password
     *
     * @return the value of tb_users.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_password
     *
     * @param userPassword the value for tb_users.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_telephone
     *
     * @return the value of tb_users.user_telephone
     *
     * @mbg.generated
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_telephone
     *
     * @param userTelephone the value for tb_users.user_telephone
     *
     * @mbg.generated
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_role
     *
     * @return the value of tb_users.user_role
     *
     * @mbg.generated
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_role
     *
     * @param userRole the value for tb_users.user_role
     *
     * @mbg.generated
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_token
     *
     * @return the value of tb_users.user_token
     *
     * @mbg.generated
     */
    public String getUserToken() {
        return userToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_token
     *
     * @param userToken the value for tb_users.user_token
     *
     * @mbg.generated
     */
    public void setUserToken(String userToken) {
        this.userToken = userToken == null ? null : userToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.user_state
     *
     * @return the value of tb_users.user_state
     *
     * @mbg.generated
     */
    public String getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.user_state
     *
     * @param userState the value for tb_users.user_state
     *
     * @mbg.generated
     */
    public void setUserState(String userState) {
        this.userState = userState == null ? null : userState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.head_image
     *
     * @return the value of tb_users.head_image
     *
     * @mbg.generated
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.head_image
     *
     * @param headImage the value for tb_users.head_image
     *
     * @mbg.generated
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage == null ? null : headImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.create_time
     *
     * @return the value of tb_users.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.create_time
     *
     * @param createTime the value for tb_users.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.update_time
     *
     * @return the value of tb_users.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.update_time
     *
     * @param updateTime the value for tb_users.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_users.online_state
     *
     * @return the value of tb_users.online_state
     *
     * @mbg.generated
     */
    public String getOnlineState() {
        return onlineState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_users.online_state
     *
     * @param onlineState the value for tb_users.online_state
     *
     * @mbg.generated
     */
    public void setOnlineState(String onlineState) {
        this.onlineState = onlineState == null ? null : onlineState.trim();
    }
}