package com.gz.tzreport.dao;

import com.gz.tzreport.pojo.TbCollection;
import java.util.List;

public interface TbCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collection
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collection
     *
     * @mbg.generated
     */
    int insert(TbCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collection
     *
     * @mbg.generated
     */
    TbCollection selectByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collection
     *
     * @mbg.generated
     */
    List<TbCollection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_collection
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCollection record);
}