package com.gz.tzreport.dao;

import com.gz.tzreport.pojo.TbPlatform;
import java.util.List;

public interface TbPlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer platformId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_platform
     *
     * @mbg.generated
     */
    int insert(TbPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_platform
     *
     * @mbg.generated
     */
    TbPlatform selectByPrimaryKey(Integer platformId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_platform
     *
     * @mbg.generated
     */
    List<TbPlatform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbPlatform record);
}