package com.gz.tzreport.dao;

import com.gz.tzreport.pojo.TbUsers;
import java.util.List;

public interface TbUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int insert(TbUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    TbUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    List<TbUsers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbUsers record);

    List<TbUsers> selectByTelephone(String telephone);
}